version: 2.1
orbs:
  node: circleci/node@1.0.1
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:10.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
